[package]
name = "ProjektEuler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.3.0"
fraction = "0.13.0"
itertools = "0.10.5"
num-bigint = "0.4"